<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Records.Recordsets.Application\Records.Recordsets.Application.csproj"/>
        <ProjectReference Include="..\Records.Recordsets.Contracts\Records.Recordsets.Contracts.csproj"/>
    </ItemGroup>

</Project>
