// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Records.Clocks.Infrastructure.Sql;

#nullable disable

namespace Records.Clocks.Infrastructure.Sql.Migrations
{
    [DbContext(typeof(ClocksDbContext))]
    [Migration("20260326204939_InitialClocks")]
    partial class InitialClocks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Records.Clocks.Infrastructure.Sql.Entities.ClockDb", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<long>("AccumulatedPauseMs")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("AtRiskAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("AtRiskDueAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("BreachDueAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("BreachedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("PauseReason")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime?>("PausedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.Property<string>("RecordsetId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.HasKey("Id");

                    b.ToTable("Clocks", (string)null);
                });

            modelBuilder.Entity("Records.Clocks.Infrastructure.Sql.Entities.ClockDefinitionDb", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<int>("AtRiskThresholdUnit")
                        .HasColumnType("int");

                    b.Property<int>("AtRiskThresholdValue")
                        .HasColumnType("int");

                    b.Property<int>("BreachThresholdUnit")
                        .HasColumnType("int");

                    b.Property<int>("BreachThresholdValue")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.HasKey("Id");

                    b.ToTable("ClockDefinitions", (string)null);
                });

            modelBuilder.Entity("Records.Clocks.Infrastructure.Sql.Entities.ClockDefinitionProjectionDb", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<int>("AtRiskThresholdUnit")
                        .HasColumnType("int");

                    b.Property<int>("AtRiskThresholdValue")
                        .HasColumnType("int");

                    b.Property<int>("BreachThresholdUnit")
                        .HasColumnType("int");

                    b.Property<int>("BreachThresholdValue")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.HasKey("Id");

                    b.ToTable("ClockDefinitionProjections", (string)null);
                });

            modelBuilder.Entity("Records.Clocks.Infrastructure.Sql.Entities.ClockProjectionDb", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<long>("AccumulatedPauseMs")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("AtRiskAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("AtRiskDueAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("BreachDueAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("BreachedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("PauseReason")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime?>("PausedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.Property<string>("RecordsetId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.HasKey("Id");

                    b.ToTable("ClockProjections", (string)null);
                });

            modelBuilder.Entity("Records.Clocks.Infrastructure.Sql.Entities.HolidayDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsObserved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("TenantId")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.HasKey("Id");

                    b.ToTable("Holidays", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
