// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Records.Notifications.Infrastructure.Sql;

#nullable disable

namespace Records.Notifications.Infrastructure.Sql.Migrations
{
    [DbContext(typeof(NotificationsDbContext))]
    partial class NotificationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Records.Notifications.Infrastructure.Sql.Entities.DeliveryAttemptDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<TimeSpan?>("NextRetryAfter")
                        .HasColumnType("time(6)");

                    b.Property<string>("NotificationId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt");

                    b.HasIndex("NotificationId");

                    b.ToTable("NotificationDeliveryAttempts", (string)null);
                });

            modelBuilder.Entity("Records.Notifications.Infrastructure.Sql.Entities.NotificationDb", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<string>("ContentBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentSubject")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("ContentTemplateDataJson")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<string>("ContentTemplateId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("NotificationRuleId")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RecipientAddress")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("RecipientDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("RecipientMetadataJson")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<string>("RecipientUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<int?>("RecordId")
                        .HasColumnType("int");

                    b.Property<string>("RecordsetId")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("ScheduleJson")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<DateTime?>("ScheduledFor")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<int>("TriggerType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("NotificationRuleId");

                    b.HasIndex("RecipientUserId");

                    b.HasIndex("RecordsetId");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.HasIndex("RecipientUserId", "ReadAt");

                    b.HasIndex("Status", "ScheduledFor");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Records.Notifications.Infrastructure.Sql.Entities.NotificationProjectionDb", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BouncedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastFailureReason")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("QueuedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RecipientUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<int?>("RecordId")
                        .HasColumnType("int");

                    b.Property<string>("RecordsetId")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<DateTime?>("ScheduledFor")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<int>("TriggerType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecordsetId");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.HasIndex("RecipientUserId", "Status");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("NotificationProjections", (string)null);
                });

            modelBuilder.Entity("Records.Notifications.Infrastructure.Sql.Entities.NotificationRuleDb", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("ChannelsJson")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RecordsetId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("ScheduleJson")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<string>("TemplateId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("TriggerJson")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<int>("TriggerType")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RecordsetId");

                    b.HasIndex("UserId");

                    b.HasIndex("RecordsetId", "TriggerType");

                    b.HasIndex("RecordsetId", "IsActive", "IsDeleted");

                    b.ToTable("NotificationRules", (string)null);
                });

            modelBuilder.Entity("Records.Notifications.Infrastructure.Sql.Entities.DeliveryAttemptDb", b =>
                {
                    b.HasOne("Records.Notifications.Infrastructure.Sql.Entities.NotificationDb", "Notification")
                        .WithMany("DeliveryAttempts")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("Records.Notifications.Infrastructure.Sql.Entities.NotificationDb", b =>
                {
                    b.HasOne("Records.Notifications.Infrastructure.Sql.Entities.NotificationRuleDb", "NotificationRule")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationRuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NotificationRule");
                });

            modelBuilder.Entity("Records.Notifications.Infrastructure.Sql.Entities.NotificationDb", b =>
                {
                    b.Navigation("DeliveryAttempts");
                });

            modelBuilder.Entity("Records.Notifications.Infrastructure.Sql.Entities.NotificationRuleDb", b =>
                {
                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
