// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Records.Recordsets.Infrastructure.Sql;

#nullable disable

namespace Records.Recordsets.Infrastructure.Sql.Migrations
{
    [DbContext(typeof(RecordsetsDbContext))]
    [Migration("20260326212612_InitialRecordsets")]
    partial class InitialRecordsets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Records.Recordsets.Infrastructure.Sql.Entities.RecordActivityDb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ActorId")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("BagJson")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("RecordId")
                        .HasColumnType("bigint");

                    b.Property<string>("RecordsetId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.HasKey("Id");

                    b.HasIndex("RecordId");

                    b.HasIndex("RecordsetId", "RecordId", "OccurredAt");

                    b.ToTable("RecordActivities", (string)null);
                });

            modelBuilder.Entity("Records.Recordsets.Infrastructure.Sql.Entities.RecordDb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BagJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RecordsetId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.HasKey("Id");

                    b.HasIndex("RecordsetId", "Id")
                        .IsUnique();

                    b.ToTable("RecordsetItems", (string)null);
                });

            modelBuilder.Entity("Records.Recordsets.Infrastructure.Sql.Entities.RecordsetColumnDb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AllowedValuesJson")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("MaxNumber")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("MinNumber")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("RecordsetDbId")
                        .HasColumnType("varchar(26)");

                    b.Property<string>("RecordsetId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("Regex")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<bool>("Required")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecordsetDbId");

                    b.HasIndex("RecordsetId", "StorageKey")
                        .IsUnique();

                    b.ToTable("RecordsetColumns", (string)null);
                });

            modelBuilder.Entity("Records.Recordsets.Infrastructure.Sql.Entities.RecordsetDb", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Recordsets", (string)null);
                });

            modelBuilder.Entity("Records.Recordsets.Infrastructure.Sql.Entities.RecordsetMigrationJobDb", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AvailableAfter")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("BackupExpiresOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BackupRecordsetId")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<DateTime?>("BackupRemovedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastError")
                        .HasColumnType("longtext");

                    b.Property<string>("NewRecordsetId")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("SourceRecordsetId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("StartedOn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.HasIndex("Stage", "AvailableAfter");

                    b.ToTable("RecordsetMigrationJobs", (string)null);
                });

            modelBuilder.Entity("Records.Recordsets.Infrastructure.Sql.Entities.RecordsetProjectionDb", b =>
                {
                    b.Property<string>("RecordsetId")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<int>("ItemCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastChangedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("RecordsetId");

                    b.ToTable("RecordsetProjections", (string)null);
                });

            modelBuilder.Entity("Records.Recordsets.Infrastructure.Sql.Entities.RecordsetStatusDb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("RecordsetDbId")
                        .HasColumnType("varchar(26)");

                    b.Property<string>("RecordsetId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.HasKey("Id");

                    b.HasIndex("RecordsetDbId");

                    b.HasIndex("RecordsetId", "Name")
                        .IsUnique();

                    b.ToTable("RecordsetStatuses", (string)null);
                });

            modelBuilder.Entity("Records.Recordsets.Infrastructure.Sql.Entities.RecordsetStatusTransitionDb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AllowedNextJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("RecordsetDbId")
                        .HasColumnType("varchar(26)");

                    b.Property<string>("RecordsetId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.HasKey("Id");

                    b.HasIndex("RecordsetDbId");

                    b.ToTable("RecordsetStatusTransitions", (string)null);
                });

            modelBuilder.Entity("Records.Recordsets.Infrastructure.Sql.Entities.RecordActivityDb", b =>
                {
                    b.HasOne("Records.Recordsets.Infrastructure.Sql.Entities.RecordDb", "Record")
                        .WithMany()
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Record");
                });

            modelBuilder.Entity("Records.Recordsets.Infrastructure.Sql.Entities.RecordsetColumnDb", b =>
                {
                    b.HasOne("Records.Recordsets.Infrastructure.Sql.Entities.RecordsetDb", null)
                        .WithMany("Columns")
                        .HasForeignKey("RecordsetDbId");
                });

            modelBuilder.Entity("Records.Recordsets.Infrastructure.Sql.Entities.RecordsetStatusDb", b =>
                {
                    b.HasOne("Records.Recordsets.Infrastructure.Sql.Entities.RecordsetDb", null)
                        .WithMany("Statuses")
                        .HasForeignKey("RecordsetDbId");
                });

            modelBuilder.Entity("Records.Recordsets.Infrastructure.Sql.Entities.RecordsetStatusTransitionDb", b =>
                {
                    b.HasOne("Records.Recordsets.Infrastructure.Sql.Entities.RecordsetDb", null)
                        .WithMany("StatusTransitions")
                        .HasForeignKey("RecordsetDbId");
                });

            modelBuilder.Entity("Records.Recordsets.Infrastructure.Sql.Entities.RecordsetDb", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("StatusTransitions");

                    b.Navigation("Statuses");
                });
#pragma warning restore 612, 618
        }
    }
}
