<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsPackable>false</IsPackable>
        <SpaRoot>..\Records.Client</SpaRoot>
        <SpaProxyLaunchCommand>npm run dev</SpaProxyLaunchCommand>
        <SpaProxyServerUrl>https://localhost:3000</SpaProxyServerUrl>
        <UserSecretsId>b6f510af-4d34-4b2f-be5f-4ebd17c324b3</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.11">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.10.0"/>
        <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.10.0-beta.1"/>
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.10.0"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.10.0"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.10.0"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.10.0"/>
        <PackageReference Include="Serilog.AspNetCore" Version="9.0.0"/>
        <PackageReference Include="Serilog.Enrichers.CorrelationId" Version="3.0.1"/>
        <PackageReference Include="Microsoft.AspNetCore.SpaProxy" Version="9.0.0"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.7.3"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Records.Client\Records.Client.esproj">
            <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
        </ProjectReference>
        <ProjectReference Include="..\Records.App.ChangeFeed\Records.App.ChangeFeed.csproj"/>
        <ProjectReference Include="..\Records.App.Infrastructure.Security\Records.App.Infrastructure.Security.csproj"/>
        <ProjectReference Include="..\Modules\Clocks\Records.Clocks.Application\Records.Clocks.Application.csproj"/>
        <ProjectReference Include="..\Modules\Clocks\Records.Clocks.Infrastructure.Sql\Records.Clocks.Infrastructure.Sql.csproj"/>
        <ProjectReference Include="..\Modules\Clocks\Records.Clocks.Presentation\Records.Clocks.Presentation.csproj"/>
        <ProjectReference Include="..\Modules\Core\Records.Core.Infrastructure.Sql\Records.Core.Infrastructure.Sql.csproj"/>
        <ProjectReference Include="..\Modules\Notifications\Records.Notifications.Application\Records.Notifications.Application.csproj"/>
        <ProjectReference Include="..\Modules\Notifications\Records.Notifications.Infrastructure.Sql\Records.Notifications.Infrastructure.Sql.csproj"/>
        <ProjectReference Include="..\Modules\Notifications\Records.Notifications.Presentation\Records.Notifications.Presentation.csproj"/>
        <ProjectReference Include="..\Modules\Recordsets\Records.Recordsets.Application\Records.Recordsets.Application.csproj"/>
        <ProjectReference Include="..\Modules\Recordsets\Records.Recordsets.Infrastructure.Sql\Records.Recordsets.Infrastructure.Sql.csproj"/>
        <ProjectReference Include="..\Modules\Recordsets\Records.Recordsets.Presentation\Records.Recordsets.Presentation.csproj"/>
        <ProjectReference Include="..\Modules\Tenants\Records.Tenants.Application\Records.Tenants.Application.csproj"/>
        <ProjectReference Include="..\Modules\Tenants\Records.Tenants.Infrastructure.Sql\Records.Tenants.Infrastructure.Sql.csproj"/>
        <ProjectReference Include="..\Modules\Tenants\Records.Tenants.Presentation\Records.Tenants.Presentation.csproj"/>
        <ProjectReference Include="..\Modules\Users\Records.Users.Application\Records.Users.Application.csproj"/>
        <ProjectReference Include="..\Modules\Users\Records.Users.Infrastructure.Sql\Records.Users.Infrastructure.Sql.csproj"/>
        <ProjectReference Include="..\Modules\Users\Records.Users.Presentation\Records.Users.Presentation.csproj"/>
    </ItemGroup>

</Project>
